config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'following' => 'following#show'
  get 'follower' => 'follower#show'

	resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :categories
  resources :words
  resources :lessons
  resources :relationships, only: [:create, :destroy, :show]
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :learneds, dependent: :destroy

  accepts_nested_attributes_for :questions

  scope :learned_words, -> learned_word_ids {where(id: learned_word_ids)}
  scope :not_learned_words, -> learned_word_ids {where.not(id: learned_word_ids)}

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @categories = Category.all.map{|c| [c.descript, c.id]}
    @categories = @categories.insert(0, ['All', 'all'])

    if params[:category_id] && params[:category_id] != 'all'
      @category = Category.find params[:category_id]
      @words = filter_by params[:learned], @category.words
    else
      @words = Word.all
      @words = filter_by params[:learned], @words
    end
  end

  def edit
    @word = Word.find params[:id]
  end

  def update
    @word = Word.find params[:id]
    if @word.update_attributes word_params
      redirect_to words_path
    else
      render 'edit'
    end
  end

  def destroy
    Word.find(params[:id]).destroy
    flash[:success] = "Word deleted"
    redirect_to words_path
  end

  private

  def word_params
    params.require(:word).permit :id, questions_attributes: [:id, :answer, :check]
  end

  def filter_by state, words
    @learned_word_ids = Learned.word_learned_ids current_user.id
    if state == 'learned'
      words.learned_words @learned_word_ids
    elsif state == 'not learned'
      words.not_learned_words @learned_word_ids
    else
      words
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_question_fields.html.erb
<p>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :answer %>
  <%= f.check_box :check %>
</p>

app/views/words/_word.html.erb
<li>
  <span><%= word.name %></span>
  <span><%= word.mean %></span>
</li>

app/views/words/_word_fields.html.erb
<p>
  <h3>Word : </h3>
  <%= f.text_area :name %><br />
  <%= f.text_area :mean %>
</p>
<%= f.fields_for :questions do |builder| %>
  <%= render 'words/question_fields', :f => builder %>
<% end %>

app/views/words/edit.html.erb
<% provide(:title, "Edit Word") %>
<h1>Update your word</h1>
<%= form_for @word do |f| %>
  <h3><%= @word.name %></h3>
  <ul>
    <%= f.fields_for :questions do |q| %>
      <li>
        <span><%= q.text_field :answer %></span>
        <span><%= q.radio_button :check, checked: true %></span>
      </li>
    <% end %>
  </ul>
  <div>
    <%= f.submit "Submit", id:"btnSubmit", class:"button btn btn-primary" %>
  </div>
<% end %>

app/views/words/index.html.erb
<h1>Listing Words</h1>
<h3>Category</h3>
<%= form_tag(words_path, :method => "get") do %>
  <%= select_tag(:category_id, options_for_select(@categories, selected: params[:category_id]),
    onchange: 'this.form.submit()')%>

  <% ['learned', 'not learned', 'all'].each do |item| %>
    <%= item %>
    <%= radio_button_tag :learned, item, false,
      checked: params[:learned] == item,
      onclick: 'this.parentNode.submit()' %>
  <% end %>
<% end %>

<ol>
  <% @words.each do |word| %>
  <li>
    <span><%= word.name %></span>
    <span><%= word.mean %></span>
    <% if current_user.admin? %>
      <span><%= link_to "edit", edit_word_path(word) %></span>
      <span><%= link_to "delete", word, method: :delete, data: {confirm: "Are you sure?"} %></span>
    <% end %>
  </li>
  <% end %>
</ol>