config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'following' => 'following#show'
  get 'follower' => 'follower#show'

	resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :categories
  resources :words
  resources :lessons
  resources :relationships, only: [:create, :destroy, :show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  accepts_nested_attributes_for :words
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find params[:id]
  end

  def edit
    @category = Category.find params[:id]
    @word = @category.words.build
    4.times {@word.questions.build}
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit :id, words_attributes: [:id, :name, :mean], questions_attributes: [:id, :answer, :check]
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Adding more words</h1>
<%= @category.descript %>
<%= form_for @category do |f| %>
  <p>
    <%= f.label :descript %>
  </p>
  <%= f.fields_for :words, @word do |builder| %>
    <%= render 'words/word_fields', :f => builder %>
  <% end %>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Catergories<h1>
<ol>
  <% @categories.each do |category| %>
    <li><%= category.descript %>
    <% if category.words.any? %>
        <% @words = category.words %>
        <h4>Word (<%= category.words.count %>)</h4>
        <ol>
          <%= render @words %>
        </ol>
        <ol>
        <h3>
          <%= link_to "Add Words", edit_category_path(category) %>
        </h3>
        <h3>
          <% @lesson = current_user.lessons.build() %>
          <%= form_for(@lesson) do |f| %>
            <%= hidden_field_tag :category_id, category.id %>
            <%= f.submit "Start Lesson", class: "btn btn-primary" %>
          <% end %>
        </h3>
      </ol>
      <% end %>
    </li>
  <% end %>
<ol>

app/views/categories/show.html.erb
<ol>
    <li><%= @category.id %></li>
    <li><%= @category.descript %></li>
<ol>